{% set name = "check-manifest" %}
{% set version = "0.39" %}
{% set sha256 = "a4c555f658a7c135b8a22bd26c2e55cfaf5876e4d5962d8c25652f2addd556bc" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: python
  entry_points:
    - check-manifest = check_manifest:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - check-manifest --help

about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENCE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
