{% set version = "0.41" %}

package:
  name: check-manifest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/check-manifest/check-manifest-{{ version }}.tar.gz
  sha256: 88afe85b751717688f8bc3b63d9543d0d962da98f1f420c554eaeb8d76c571a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - check-manifest = check_manifest:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - toml

test:
  commands:
    - check-manifest --help

about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
    - ocefpaf
