{% set version = "0.50" %}

package:
  name: check-manifest
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/check-manifest/check_manifest-{{ version }}.tar.gz
  sha256: d300f9f292986aa1a30424af44eb45c5644e0a810e392e62d553b24bb3393494

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - check-manifest = check_manifest:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - python-build >=0.1
    - setuptools
    - toml

test:
  imports:
    - check_manifest
  commands:
    - pip check
    - check-manifest --help
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
    - ocefpaf
