{% set name = "check-manifest" %}
{% set version = "0.38" %}
{% set sha256 = "dba4749e3874d8f83eb4f0814c9c331fcade6c6325f885deb7b14aa1487fb323" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: python
  entry_points:
    - check-manifest = check_manifest:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - check-manifest --help

about:
  home: https://github.com/mgedmin/check-manifest
  license: MIT
  license_family: MIT
  license_file: LICENCE.rst
  summary: Check MANIFEST.in in a Python source package for completeness

extra:
  recipe-maintainers:
    - hodgsonw
